language: python
python:
  - "2.7"
  - "3.2"
  - "3.4"
install:
  - pip install pytest-cov
  - pip install Sphinx
  - pip install coveralls

script:
  - py.test --cov .
  - sh -c 'cd docs && make html'
after_success:
  coveralls
